app.py
import os
from flask import Flask
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

def create_app():
    app = Flask(__name__)
    client = MongoClient(os.environ.get("MONGODB_URI"))
    app.db = client.habitTracker

    app.register_blueprint(pages)

    return app

routes.py
import datetime
import uuid
from collections import defaultdict
from flask import Blueprint, render_template, request, request_started, redirect, url_for, current_app

pages = Blueprint("habits", __name__, template_folder="templates", static_folder="static")


@pages.context_processor
def add_calc_date_range():
    def date_range(start: datetime.datetime):
        dates= [start + datetime.timedelta(days=day) for day in range(-3,4)]
        return dates
    return {"date_range": date_range}

def today_at_midnight():
    today= datetime.datetime.today()
    return datetime.datetime(today.year, today.month, today.day)

@pages.route("/")
def index():

    date_str= request.args.get("date")

    if date_str:
        selected_date= datetime.datetime.fromisoformat(date_str)
    else:
        selected_date=today_at_midnight()
    
    habits_on_date = current_app.db.habits.find({"added":{"$lte": selected_date}})
    completions = [
        habit["habit"]
        for habit in current_app.db.completions.find({"date": selected_date})
    ]

    return render_template(
        "index.html",
         habits=habits_on_date,
         selected_date=selected_date,
         completions=completions,
         title="Habit Tracker - Home",  
        )

@pages.route("/add", methods=["GET", "POST"])
def add_habit():
    today = today_at_midnight()

    if request.method:
        current_app.db.habits.insert_one(
            {"_id": uuid.uuid4().hex, "added": today, "name": request.form.get("habit")}
        )

    return render_template(
        "add_habit.html", 
        title="Habit Tracker - Add Habit", 
        selected_date= today,
    )

@pages.route("/complete", methods=["POST"])
def complete():
    date_string = request.form.get("date")
    habit = request.form.get("habitName")
    date = datetime.datetime.fromisoformat(date_string)
    current_app.db.completions.insert_one({"date": date, "habit": habit})

    return redirect(url_for(".index", date=date_string))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}
    <form class="form" method="POST">
        <textarea class="form__input" name="habit" id="habit" rows="3" placeholder="Anade un habito nuevo"></textarea>
        <button class="form__button" type="submit">add</button>
    </form>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
<section class="habitlist">
{% for habit in habits %}
        {% set completed = habit["_id"] in completions %}
        {% if completed %}
            <div class="habit completed">
                <p class="habit__name">
                    {{ habit["name"] }}
                </p>
                <svg class="habit__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>                
            </div>
        {% else %}
            <div class="habit">
                <form method="POST" class="habit__form" action="{{ url_for('habits.complete') }}">
                <input type="hidden" id="habitId" name="habitId" value="{{ habit['_id'] }}" />
                <input type="hidden" id="date" name="date" value="{{ selected_date }}" />
                <button type="submit" class="habit__button">
                        {{ habit["name"] }}
                </button>
                </form>
            </div>
        {% endif %}
{% endfor %}
</section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=divice-width, initial-scale=1.0"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
        <title>{{ title }}</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

        {% block head_content %} {% endblock %}
    </head>
    <body>
        <header class="header">
            <h1 class="header__logo"><a href="{{ url_for('habits.index') }}" class="header__link">Habits</a></h1>

            {% if "add" not in request.endpoint %}
                <a href="{{ url_for('habits.add_habit') }}" class="header__link">+ Add new</a>
            {% endif %}

        </header>
        <main class="main">
            <section class="dates">
                {% for date in date_range(selected_date) %}
                    <a 
                        class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else ''}}"
                        href="{{ url_for('habits.index', date=date) }}"
                    >
                        <time class="date" datetime="{{ date }}">
                            <span>{{ date.strftime("%a") }}</span>
                            <span>{{ date.strftime("%d") }}</span>
                        </time>
                    </a>
                {% endfor %}
            </section>
            
            {% block main_content %} 
            {% endblock %}
        </main>
    </body>
</html>